imports:
    - { resource: config.yml }

framework:
#    validation:
#        cache: apc
    session:
        save_path: %kernel.root_dir%/path/to/memcache/server/sessions
        name: acme_app
        cookie_lifetime: 2520 # 42 minutes in seconds

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
